@startuml
title 11-b(1) Modeling Value to Stakeholder
archimate #Motivation "Stakeholer" <<stakeholder-filled>>
(AssetValue)
circle association
rectangle Asset
Stakeholer - association
association - Asset
AssetValue -- association : ""
@enduml